version: '3.1'

services:

  db:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    container_name: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: example
